### ISSUE TITLE
Game not launching, Antimalware Service Executable

### ISSUE THREAD

**Issue by cadusouza** [BrianLima/UWPHook#92]
Any game I add on STEAM via UWPHook is not being playable.

On Steam the game says it's running, but it doesn't.

Also my windows Antimalware Service Executable goes into overdrive using high amounts of CPU and Memory

does anyone know how to fix this issue?

**Comment by bublz00** [comment]
I am having the same issue!  Steam says it's running but the Antimalware executable goes haywire.  I tried a few things to fix it but I can't get any other outcomes.  I played around a bit with the Windows Defender settings, no luck.  Tried running UWPHook as admin and then adding the app, no luck.  I'm not exactly a "power user" so that's all I've tried so far.  If I have any luck, I'll update.

I can open the games just fine through the Xbox app.

**Comment by AnthonMS** [comment]
Having the same issue. Let me know if there is anything I can assist with by handing over a log or some manual debugging or something.

**Comment by RyanPMcL** [comment]
Same issue. Nothing actually launches, it just appears as running in Steam.

**Comment by TheBingPlays** [comment]
ditto on this issue.

**Comment by ibrabeicker** [comment]
+1

**Comment by BrianLima** [comment]
Hi, i know that this has been reported for a while, but i couldn't yet find a cause, i had little to no time to work on this issue because of my personal life and job needing much more time than the expected in the last year, so i'm taking a vacation during August and will do my best once i'm back to understand and fix this issue. In the meantime if someone applies a patch that fix the issue, i could try to make a beta release and contact some of the people either here or on Reddit to test it.

**Comment by GianCarlosB** [comment]
Same thing here.

**Comment by shgaspardr** [comment]
Same here!

**Comment by RyanPMcL** [comment]
Today I was able to launch UWP games from steam. Not sure what I changed, but it works for me now.

**Comment by bublz00** [comment]
> Today I was able to launch UWP games from steam. Not sure what I changed, but it works for me now.

I still can't open them.  I checked Windows Update and saw an update for Windows Defender but even after installing that, I'm getting the same results.

**Comment by retribyte** [comment]
Having the same issue.

**Comment by Shiroe93** [comment]
Having the same issue.

**Comment by TheBingPlays** [comment]
> @BrianLima Having the same issue, but i found that if you check the "run as admin" in the option it starts to work again so i think that's an authorization problem

Run what as admin? steam or UWPHook? run both as admin and no luck

**Comment by Shiroe93** [comment]
you go in to uwphook shortcut proprieties --> compatibility tab and check ran as adimin and apply 
now when you start the game on steam a security pop-up from windows will appear click yes and the game should be starting normally 
WARNING: i spoke to the developer on twitter and he does't advise this solution  (because is obviously a security risk) 
personally i totaly agree and my previous comment was intended to help him better understand the issue not to be used by a end user infact i disabled it myself as soon as i've finished testing

**Comment by nazsol** [comment]
Same problem here, the above fix does work but like said it is a security risk and also Steam does not show you are playing a game.

**Comment by BrianLima** [comment]
Hi people, we have a new release, could someone who has thiss problem currently give it a try and see if it works?

https://github.com/BrianLima/UWPHook/releases/tag/2.11.0

**Comment by nazsol** [comment]
> Hi people, we have a new release, could someone who has thiss problem currently give it a try and see if it works?
> 
> https://github.com/BrianLima/UWPHook/releases/tag/2.11.0

Same problem as before for me unfortunately. 

I added 14 games and only 4 launch.

The games that aren't launching are -
Besiege 
Descenders 
Dragon Ball Fighters 
Golf With Your Friends 
Lemnis Gate 
Mortal Kombat 11 
Sniper Elite 5 
Teenage Mutant Ninja Turtles: Shredder's Revenge 
Turbo Golf Racing 
Worms W.M.D 

On a plus note Antimalware isn't going off like it did before and Steamgrid images are working whereas previously they didn't.

**Comment by TheKerevas** [comment]
It also happens to me with Forza Horizon 5, I click on Play but nothing happens, I have no problems with antivirus

**Comment by stevealexandre** [comment]
Guys, look at #93 fix is coming before the end of the week. Working on it ✌

**Comment by alex-brunskill** [comment]
@stevealexandre - cheers for working on this, any news on when the fix will be merged and released?

**Comment by BrianLima** [comment]
I'm reviewing it still

**Comment by stevealexandre** [comment]
The fix is available right now.
To all, download the last release and you will have to delete and create again all your games to enjoy the fix.

**Comment by alex-brunskill** [comment]
Thank you, unfortunately though I'm still having the same issue. I click play, an installing first time setup window comes up but nothing more.

**Comment by stevealexandre** [comment]
Hum, let me take a look, I will install halo wars to check it.
Do you confirm you have download the last release published today and import all your games again ?

**Comment by alex-brunskill** [comment]
I have re-installed the three games it found, the .exe doesn't seem to work for me either. Had to download the .zip and extract, then run which worked. 2.11.0 worked for me, 2.12.0 didn't.

**Comment by TheKerevas** [comment]
Once installed the installer does not work, opening from the Zip yes. I noticed that UWPHook no longer finds all my Microsoft apps but only Forza Horizon 5 which is the only Microsoft Store game installed. Starting Forza Horizon 5 it tells me "Access to path 'C: \ Program Files (x86) \ Briano \ UWPHook \ debug.log' denied"

**Comment by stevealexandre** [comment]
@BrianLima I confirm on my side too the installer install a version which not working (process start and instant killed. Seems like an error somewhere. Maybe should be a good idea to put some error log on real error with the logger I've added to follow them easier).

@alex-brunskill can you confirm me which halo wars? 1 or 2 or both? Unfortunately, if microsoft does not create the right manifest, we will have some trouble to handle them at the moment.
On the 3 games found, they are working ? If not, list them to take a look.

**Comment by stevealexandre** [comment]
> Once installed the installer does not work, opening from the Zip yes. I noticed that UWPHook no longer finds all my Microsoft apps but only Forza Horizon 5 which is the only Microsoft Store game installed. Starting Forza Horizon 5 it tells me "Access to path 'C: \ Program Files (x86) \ Briano \ UWPHook \ debug.log' denied"

Interesting issue. Will create a fix for the logger to create them in the appdata because program files needs always admin permissions. About other microsoft apps, it's a normal behavior, we are looking for manifest and executable right now and integrated apps does not have the same structure. Since it was design I think to handle game, it will be difficult to handle all cases.

**Comment by alex-brunskill** [comment]
@stevealexandre it was both Halo Wars 1 & 2. When I rerun the hook, via the zip it doesn't find those games at all now. Only Gears Tactics, Mutant Year Zero and Just Cause 4. These have never launched for me.

**Comment by TheKerevas** [comment]
> Interesting issue. Will create a fix for the logger to create them in the appdata because program files needs always admin permissions. About other microsoft apps, it's a normal behavior, we are looking for manifest and executable right now and integrated apps does not have the same structure. Since it was design I think to handle game, it will be difficult to handle all cases.

It goes what it finds only the games, it is more "clean" than it shows from the list. Anyway I was hoping to be able to play Forza Horizon 5 from Steam today, but I still see not xD

**Comment by stevealexandre** [comment]
> > Interesting issue. Will create a fix for the logger to create them in the appdata because program files needs always admin permissions. About other microsoft apps, it's a normal behavior, we are looking for manifest and executable right now and integrated apps does not have the same structure. Since it was design I think to handle game, it will be difficult to handle all cases.
> 
> It goes what it finds only the games, it is more "clean" than it shows from the list. Anyway I was hoping to be able to play Forza Horizon 5 from Steam today, but I still see not xD

Install the app in other directory which does not need admin permissions like an other drive or at the root of C.
@BrianLima Maybe a good idea to configure the installer on the default path to C:\Users\<username>\AppData\Local like some apps to avoid admin permissions issues needed.

**Comment by BrianLima** [comment]
Hey, i've removed the installer version from the current release, i will be doing a new release once i figure out a fix and probably a proper logger, it was on my to do list for a while, maybe in the end the best would be to handle the child process in the 2.11 way for apps without executables and 2.12 for newer apps and not exclude apps from the powershell result if they do not have an executable.

**Comment by stevealexandre** [comment]
> Hey, i've removed the installer version from the current release, i will be doing a new release once i figure out a fix and probably a proper logger, it was on my to do list for a while, maybe in the end the best would be to handle the child process in the 2.11 way for apps without executables and 2.12 for newer apps and not exclude apps from the powershell result if they do not have an executable.

I'm close to push a PR with user configuration for level log & log creation to AppData\Roaming\Briano\UWPHook

**Comment by stevealexandre** [comment]
@BrianLima PR created for fixing log issue.
I'm looking right now about Halo wars issue.

**Comment by stevealexandre** [comment]
Found a possible fix but take back a lot of "basic apps".
I'm testing it right now with this list of games :
[] - MFS2020
[] - Forza 5
[] - Halo master chief edition
[] - Myst
[] - Farming Simulator 22
[] - Train Sim World 3
[] - Halo Wars 1 & 2

_List status will be updated after tests on this response_

**Comment by stevealexandre** [comment]
PR #98 + #99 are created. Waiting action from @BrianLima right now to review, merge and generate all the needed to fix issues.

**Comment by borg100** [comment]
> PR #98 + #99 are created. Waiting action from @BrianLima right now to review, merge and generate all the needed to fix issues.

Any chance you can share a build with your fixes?

**Comment by stevealexandre** [comment]
> > PR #98 + #99 are created. Waiting action from @BrianLima right now to review, merge and generate all the needed to fix issues.
> 
> Any chance you can share a build with your fixes?

Brian is currently reviewing them and merging.
I'm waiting for it since on my side, I have an issue which doesn't allow me anymore to run game through steam without launching UWPHook with run as admin option.
He has merged one of two a few minutes and I think he will merge the second before the end of the day with the release.

**Comment by BrianLima** [comment]
Hey, i've reviewed both PR's and did the tests, everything, is ok, i'll do the release later today. 

For it, i will be changing the path for the installation to try to avoid the admin rights issue.

**Comment by BrianLima** [comment]
Hey, the new release is pushed: https://github.com/BrianLima/UWPHook/releases/tag/2.13.0
Could you guys report if the newer fixes and the new install location improve this behavior?

**Comment by borg100** [comment]
Thanks for the update.

Unfortunately, it doesn't appear to be working for these games:
- Yakuza: Like a Dragon
- PowerWash Simulator

But the games do run if I execute the command directly in a command prompt window.

**Comment by stevealexandre** [comment]
> Thanks for the update.
> 
> Unfortunately, it doesn't appear to be working for these games:
> 
> * Yakuza: Like a Dragon
> * PowerWash Simulator
> 
> But the games do run if I execute the command directly in a command prompt window.

Only for these two games ? Are you able to run other games?

**Comment by BrianLima** [comment]
Both PowerWash and Yakuza LAD work fine on my end, have you removed the games from your library and re-imported them in the new version @borg100?

**Comment by TheKerevas** [comment]
Forza Horizon 5 doesn't work. I reinstalled UWPHook and re-added the game but nothing. I click on play, I appear on Steam that I have opened the game but then it disappears

**Comment by borg100** [comment]
@stevealexandre I made a list of the games I tried.

Working:
- Donut County
- Grounded
- Minecraft for Windows 10
- Tell Me Why

Not working:
- Craftopia
- Embr
- Human Fall Flat
- Minecraft Dungeons
- No Man's Sky
- PowerWash Simulator
- Yakuza: Like a Dragon

@BrianLima I did and verified in Steam; all games are using the latest version of UWPHook.

**Comment by stevealexandre** [comment]
@TheKerevas and @borg100 could you try to configure UWPHook to run as admin in his compatibility option? (Option available in properties of the exe file in compatibility tab)

**Comment by borg100** [comment]
@stevealexandre After enabling the "run as admin" option, the game launches as expected (following UAC prompt).

**Comment by borg100** [comment]
> Ok thanks for the test. Last question, can you confirm you have your windows updated ?

Actually, I haven't used this PC in a while and automatic updates have been disabled. I'll update Windows and then try again without the compatibility option and report back.

**Comment by stevealexandre** [comment]
> > Ok thanks for the test. Last question, can you confirm you have your windows updated ?
> 
> I haven't used this PC in a while and automatic updates have been disabled. I'll update Windows and then try again without the compatibility option and report back.

Thanks for the information.
Interesting to see the launch seems random following computer.
Could you try this version [2.14.0b](https://github.com/stevealexandre/UWPHook/releases/tag/2.14.0b) ? I have implemented a new way to start apps and to check if is running.

**Comment by borg100** [comment]
@stevealexandre No change after updating Windows and using v2.13.

> Could you try this version [2.14.0b](https://github.com/stevealexandre/UWPHook/releases/tag/2.14.0b) with your games listed ? I have implemented a new way to start apps and to check if is running.

@stevealexandre The games are launching now. Thanks for working on this. 👍 

I noticed a few bugs, just wanted to mention it in case you weren't aware.

1. The export function is broken. The shortcuts were not created. I had to use v2.13 to create the shortcuts and then manually change the target paths in Steam.

![Screenshot 2022-09-19 094933](https://user-images.githubusercontent.com/62734792/191033748-3a444ca9-df98-4bc4-aee0-c5c055e4684c.png)

2. If you enable the "streaming mode" option, the game does not launch anymore.

**Comment by stevealexandre** [comment]
> @stevealexandre No change after updating Windows and using v2.13.
> 
> > Could you try this version [2.14.0b](https://github.com/stevealexandre/UWPHook/releases/tag/2.14.0b) with your games listed ? I have implemented a new way to start apps and to check if is running.
> 
> @stevealexandre The games are launching now. Thanks for working on this. 👍
> 
> I noticed a few bugs, just wanted to mention it in case you weren't aware.
> 
> 1. The export function is broken. The shortcuts were not created. I had to use v2.13 to create the shortcuts and then manually change the target paths in Steam.
> 
> ![Screenshot 2022-09-19 094933](https://user-images.githubusercontent.com/62734792/191033748-3a444ca9-df98-4bc4-aee0-c5c055e4684c.png)
> 
> 2. If you enable the "streaming mode" option, the game does not launch anymore.

I have tried Embr with my release and everything is working on my side without any issue on export.
Same for streaming option, working on my side.
Both of these functionnalities are not being modified in my release.

**Comment by stevealexandre** [comment]
Ok found the issue, for moment, get your api key in the setting of uwphook (click on key, login on the website steamgriddb et get your key)

**Comment by TheKerevas** [comment]
> @TheKerevas and @borg100 could you try to configure UWPHook to run as admin in his compatibility option? (Option available in properties of the exe file in compatibility tab) ![Run as admin](https://github.com/stevealexandre/UWPHook/blob/ef272888ae3fc176d30733171cc56f82aac558a8/ezgif.com-gif-maker.gif?raw=true) [ ![Run as admin](https://github.com/stevealexandre/UWPHook/blob/ef272888ae3fc176d30733171cc56f82aac558a8/ezgif.com-gif-maker.gif?raw=true) ](https://github.com/stevealexandre/UWPHook/blob/ef272888ae3fc176d30733171cc56f82aac558a8/ezgif.com-gif-maker.gif?raw=true) [ ](https://github.com/stevealexandre/UWPHook/blob/ef272888ae3fc176d30733171cc56f82aac558a8/ezgif.com-gif-maker.gif?raw=true)

Same problem, not even putting as administrator as you said I solved

**Comment by TheKerevas** [comment]
> > > Ok thanks for the test. Last question, can you confirm you have your windows updated ?
> > 
> > 
> > I haven't used this PC in a while and automatic updates have been disabled. I'll update Windows and then try again without the compatibility option and report back.
> 
> Thanks for the information. Interesting to see the launch seems random following computer. Could you try this version [2.14.0b](https://github.com/stevealexandre/UWPHook/releases/tag/2.14.0b) with your games listed ? I have implemented a new way to start apps and to check if is running.

With this version everything works perfectly on Forza Horizon 5

**Comment by stevealexandre** [comment]
@TheKerevas can you try this latest fix to have icons without api key please with your games ?
https://github.com/stevealexandre/UWPHook/releases/tag/2.14.1b

Thanks.

**Comment by XmutanoX** [comment]
Just to add to this thread, tried to play Metal Hellsinger and Moonscars:

2.13 exe on default folder: Import grid works but both games won't launch
2.13 zip on desktop: Same problem
2.14.1 on desktop: Both games launch without a problem but steamgrid doesn't so no icons on steam

**Comment by Noughter** [comment]
I got the same problem and all the Games i add on Steam won't start. I tried using the 2.14.1b prerelease but that one is just crashing on startup for me not sure what i can do

**Comment by XmutanoX** [comment]
> > Just to add to this thread, tried to play Metal Hellsinger and Moonscars:
> > 2.13 exe on default folder: Import grid works but both games won't launch 2.13 zip on desktop: Same problem 2.14.1 on desktop: Both games launch without a problem but steamgrid doesn't work so no icons on steam
> 
> Do you have tried the 2.14.1b ? What do you mean by streamgrid doesn't work? by putting your api key or without? Did you get an error popup?

Oh i'm sorry the lack of info and my mistake aswell, yes it was 2.14.1b but only the little icons by the side were missing, not the big ones on steamgrid. I used my API key, both were successfully exported and no errors.

![image](https://user-images.githubusercontent.com/105004950/193909095-5df37b34-14ee-4545-9603-cd06afe4797d.png)

![image](https://user-images.githubusercontent.com/105004950/193908492-726f0ddb-b8ad-4672-af21-6a90378f13cd.png)

**Comment by stevealexandre** [comment]
> > > Just to add to this thread, tried to play Metal Hellsinger and Moonscars:
> > > 2.13 exe on default folder: Import grid works but both games won't launch 2.13 zip on desktop: Same problem 2.14.1 on desktop: Both games launch without a problem but steamgrid doesn't work so no icons on steam
> > 
> > 
> > Do you have tried the 2.14.1b ? What do you mean by streamgrid doesn't work? by putting your api key or without? Did you get an error popup?
> 
> Oh i'm sorry the lack of info and my mistake aswell, yes it was 2.14.1b but only the little icons by the side were missing, not the big ones on steamgrid. I used my API key, both were successfully exported and no errors.
> 
> ![image](https://user-images.githubusercontent.com/105004950/193909095-5df37b34-14ee-4545-9603-cd06afe4797d.png)
> 
> ![image](https://user-images.githubusercontent.com/105004950/193909331-7d155902-8b09-4035-883b-9ed79c2631ee.png)

Ok thanks for the info. Will take a look before the end of the week with the two games given and give you an update of the analyze.

**Comment by stevealexandre** [comment]
> 1+ still same issue
> Just downloaded the latest version none of my added games will launch

Which version exactly and which game? Did you try the 2.14.1b?

**Comment by matt0903** [comment]
> 1+ still same issue
> Just downloaded the latest version none of my added games will launch

Same issue here as well. Using 1.14.1b. 
Tested on Age Of Empires V will test some more soon.

**Comment by SpeedyLom** [comment]
2.14.1b fixes the issue I was having opening Slay the Spire, many thanks for your hard work! 😁

**Comment by stevealexandre** [comment]
@XmutanoX new release with a fix for your two games [2.15.0](https://github.com/stevealexandre/UWPHook/releases/tag/2.15.0)
@matt0903 I assume you're talking about AOE IV and not V which does not exist in the current world. Checkout my new release [2.15.0](https://github.com/stevealexandre/UWPHook/releases/tag/2.15.0). Tested and working.

**Since Brian seems away and not available, I will manage only issues submitted on my project repo from now : https://github.com/stevealexandre/UWPHook/issues.
This will be until Brian will merge my repo in his own. (The property of the app is still at Brian of course)**

**Comment by stevealexandre** [comment]
> > @BrianLima Having the same issue, but i found that if you check the "run as admin" in the option it starts to work again so i think that's an authorization problem
> 
> This worked for me although I added a step. (I'm on UWPH 2.13.0.0.)
> 
> In uwphook properties (right click on shortcut) go to _compatibility_ and then "_Change settings for all user_". Just check the _Run this program as administrator_, save, then re-add your games. Works for me, might work for you.
> 
> Games that worked after I did the above ^ Death Stranding, DJ Max V, and Scarlet Nexus

Is not recommanded to run as admin. You can create a big security breach with that. use the 2.15.1 https://github.com/stevealexandre/UWPHook/releases/tag/2.15.1 which implement a new logic to run games.
